### ISSUE TITLE
ACL_F_MODELS

### ISSUE THREAD

**Issue by Galixte** [Zoddo/phpbb-postmodels#1]
Salut,

c’est la permission de quel utilisateurs ?

``` php
    'ACL_F_MODELS'                  => 'Peut utiliser les modèles de message.',
```

**Comment by Zoddo** [comment]
C'est une permission réglable au niveau de chaque forum qui permet d'utiliser ou non les modèles dans le-dit forum.

`u_pm_models` est une permission qui autorise ou non l'utilisation des modèles dans les MP.

**Comment by Galixte** [comment]
Merci bien pour tes réponses toujours instructives.

Je me régale avec ton extensions.

Bonne continuation.
